# Generated by Django 4.1.7 on 2023-02-18 09:09

from django.db import migrations
from apps.models.admin import Admin


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    admin = Admin.objects.using(db_alias).create(
        email="admin@test.com", username="admin", fullname="Admin Admin")
    admin.set_password("123")
    admin.save()


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Admin.objects.using(db_alias).filter(email="admin@test.com").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
